### ISSUE TITLE
DevExtreme control does not display in a Visual Studio 2013 project

### ISSUE THREAD

**Issue by gmarotteck** [DevExpress/devextreme-angular2#101]
This is my first attempt at getting an Angular2 project up and running with DevExtreme controls in Visual Studio 2013. 

An Angular2 DevExtreme button has been placed between an h1 tag and an Angular2 template but it is not displaying (screenshot #1 in the attached). 

DevExtreme 16.1.5 Nuget package has been successfully installed (screenshot #2 in the attached).

The entire Visual Studio 2013 project is attached.

[FirstAngular2App.zip](https://github.com/DevExpress/devextreme-angular2/files/459051/FirstAngular2App.zip)
[Screenshots.zip](https://github.com/DevExpress/devextreme-angular2/files/459050/Screenshots.zip)

**Comment by gmarotteck** [comment]
Did the Nuget package for 16.1.5 miss dlls needed to display the button?
How do I get the button to display?

**Comment by dxvladislavvolkov** [comment]
Hello!
You need install the devextreme-angular2 npm package as follows:
npm install devextreme-angular2@16.1.5 

After that you need to connect it as shown in our example 
https://github.com/DevExpress/devextreme-angular2#add..

**Comment by gmarotteck** [comment]
Button still not showing up.
I ran the install “npm install devextreme-angular2@16.1.5” but am not sure it completed normally.  It issued lots of warnings as shown in the attached below.
Is there a way to determine if it installed correctly?
Thanks.
[Uploading DevExtreme install.docx…]()

**Comment by gmarotteck** [comment]
I ran the following:
npm install devextreme-angular2@16.1.5

Trying to get a DevExtreme button to display inside a Visual Studio 2013 project.  I tried a "Test Button 1" and "Test Button 2" on the index.html page and a " Test Button 3"  on the contact.html page but none of the buttons display.

The entire project is attached:  Can you duplicate the issue with the attached project and advise on a solution?

[FirstAngular2App.zip](https://github.com/DevExpress/devextreme-angular2/files/482646/FirstAngular2App.zip)

**Comment by dxvladislavvolkov** [comment]
You need to update your versions of node and NPM.
Also, you are using an older version of angular 2, so upgrade your Angular 2 version to the Release version and upgrade our devextreme-angular2 NPM package to 16.1.7-alpha
We do not have a template for Visual Studio that illustrates how to use Angular 2 with our widgets. At the moment, we only have a sample in this GitHub repository.
Try to create a project as [shown there](https://angular.io/docs/ts/latest/quickstart.html) and then connect it to the project in Visual Studio as shown [here](https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html).
Let me know if this is helpful

**Comment by gmarotteck** [comment]
I upgraded node and npm to the latest as shown in the attachment. 

Thank-you for the help so far ...

I set up the project according to the instructions mentioned including package.json, etc.

I upgraded DevExpreme with the following:
 npm install devextreme-angular2@16.1.7-alpha

When I run Angular it is correctly displaying results as shown below but the DevExtreme button is ignored.

Would you take a look and advise on what I should try next... … the entire project is attached.

[FirstAngular2App.zip](https://github.com/DevExpress/devextreme-angular2/files/498134/FirstAngular2App.zip)
[DevExtreme.docx](https://github.com/DevExpress/devextreme-angular2/files/498133/DevExtreme.docx)

**Comment by gmarotteck** [comment]
Closed by mistake.

I upgraded node and npm to the latest as shown in the attachment. 

Thank-you for the help so far ...

I set up the project according to the instructions mentioned including package.json, etc.

I upgraded DevExpreme with the following:
 npm install devextreme-angular2@16.1.7-alpha

When I run Angular it is correctly displaying results as shown below but the DevExtreme button is ignored.

Would you take a look and advise on what I should try next... … the entire project is attached.

[DevExtreme.docx](https://github.com/DevExpress/devextreme-angular2/files/498137/DevExtreme.docx)
[FirstAngular2App.zip](https://github.com/DevExpress/devextreme-angular2/files/498138/FirstAngular2App.zip)

**Comment by gmarotteck** [comment]
Also, all the correct levels are installed on your side ... does the DevExtreme button show up when you run it?

**Comment by Angelminster** [comment]
Hi,

The reason your button is not showed is because you haven't load devextreme-angular2 integration. You should do it inside of your system.config.js as it is said in the [main documentation](https://github.com/DevExpress/devextreme-angular2)

In your index.html you have node_modules/devextreme/dist/js/dx.all.js, Scripts/dx.web.js (twice) -> Choose one. You are referencing Jquery 1.11.3 and another JQuery inside node_modules, you should reference only the one inside node_modules (JQuery 2.3 or 2.4). You have 2 reflects, 2 zonejs, 2 dx.common.css.. dx.ligth.css and so on. I think that globalize is required too...

Then, as i said before, in your systemjs you should add devextreme-angular2. In your package,json add devextreme-angular2. Take a look at the documentation to set up a project.

**Comment by gmarotteck** [comment]
Thank-you for your recommendations.

I checked and updated my project as follows:
1.	Removed “node_modules/devextreme/dist/js/dx.all.js” from index.html.  
2.	Removed the extra 1.11.13 jQuery.
3.	Remove the duplicate reflects, zonejs, dx.common.css, dx.light, etc.
4.	Not sure what you meant by the comment: “I think that globalize is required too”.  What line were you referring to and what should I add or delete?
5.	I took another look at the documentation to set up the project.  I saw the example about devextreme-angular2 and so added the missing devextreme-angular2 to system.config.js.

My Angular2 component is still displaying but the DevExtreme button is not yet displaying.

Please take another look and let me know what to change to get the button to display.  If you could alter the project to make it display and attach the modified project that would be great.

(note:  the entire project is attached)


[DevExtreme.docx](https://github.com/DevExpress/devextreme-angular2/files/519878/DevExtreme.docx)

[FirstAngular2App.zip](https://github.com/DevExpress/devextreme-angular2/files/519876/FirstAngular2App.zip)

**Comment by Angelminster** [comment]
Use “node_modules/devextreme/dist/js/dx.all.js” and not dx.web.js (you have it twice). 
You are importing app.js as a script and with systemjs.
You still have JQuery 1.1 references on packages.config.
You are using Devextreme 16.1.5 from scripts. 
You don't have Angular 2.0.0 in your node_modules, and not even in your code. 
You don't have Angular 2 Modules

This is far from being a good project. I don't know how this configuration can build something good. I recommend you to take a sample project([example](https://github.com/mgechev/angular-seed)) and then add your code. In a regular Angular2 project you should follow the documentation guidelines and you will have a good starting point.

**Comment by gmarotteck** [comment]
I took a look at the Angular seed project link that you provided.  That project does not appear to be set up for VS2013.  My goal is to run DevExtreme controls inside a VS2013 Angular2 project.

Do you have a link to a clean VS2013 project somewhere that I could download and use a base project?

**Comment by Angelminster** [comment]
You should use vs2015 community. It's free in open source projects and you get asp.net core with tools, the future. 

With vs2013 you will get some problems to get it working inside asp.net mvc. You can do it, but is gonna be hard.

**Comment by GoshaFighten** [comment]
@gmarotteck 
I see that you wrote in a ticket in our Support Center that this issue is resolved. Can we close this issue?

**Comment by gmarotteck** [comment]
Yes, thank-you.  This is working now.
