### ISSUE TITLE
Support for Angular 2 final

### ISSUE THREAD

**Issue by marcelgood** [DevExpress/devextreme-angular2#107]
So now that the final version of Angular 2 has been released, when can we expect DevExtreme to be updated to support it and hopefully have the most major issues resolved?

**Comment by dxbykov** [comment]
Hi,
 
We'll update DevExtreme Angular 2 integration to the final Angular 2 version as soon as possible (hopefully, during a week) and are planning to release it simultaneously with the DevExtreme 16.2 release in 2-3 months.

**Comment by marcelgood** [comment]
Thanks. Does that mean there will be a new npm package within the week that we can try or do we have to wait 2-3 months?

**Comment by dxbykov** [comment]
Of course you don't have to wait 2-3 months :). We are planning to update our npm package next week. In 2-3 months we shouldn't have any showstoppers to prevent making DevExtreme Angular 2 components production-ready.

**Comment by strpipe** [comment]
Thank you

**Comment by 14Muhammad** [comment]
Is it available for final version now ?

**Comment by Aden-git** [comment]
Hello,

We are preparing the package now. If all goes according to plan, we will publish it tomorrow.

**Comment by Aden-git** [comment]
We have released version 16.1.7-alpha with support for Angular 2. The NPM package is already available for this version.

**Comment by Angelminster** [comment]
It Works without a problem. Thank You
