### ISSUE TITLE
Following the guide for integration into an existing app should mention installing jQuery

### ISSUE THREAD

**Issue by strpipe** [DevExpress/devextreme-angular2#113]
Following the guide for integration into an existing app should mention installing jQuery.
Also, it currently does not work with jQuery 3.x.x using Version 2.2.4 will work, though.

On can get this package by typing the following into the console: npm install jquery^2.2.4

**Comment by Aden-git** [comment]
Hello,

We has jQuery 2.2.3 in dependencies in [package.json](https://github.com/DevExpress/devextreme-angular2/blob/master/npm/package.json#L24), so the jQuery npm package is installed with devextreme-angular2. Also we have a note in the ["Adding DevExteme widgets to an Angular 2 application"](https://github.com/DevExpress/devextreme-angular2/blob/master/README.md#adding-devexteme-widgets-to-an-angular-2-application) section about adding a jQuery script tag to index.html.
