### ISSUE TITLE
Add this custom component to grid in example project

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular2#118]
[componentcodes-ts file.docx](https://github.com/DevExpress/devextreme-angular2/files/486685/componentcodes-ts.file.docx)

**Comment by GoshaFighten** [comment]
I have to reject your suggestion to add this custom component to our examples. In our example, we demonstrate common principles of working with widgets. But, in your code, you illustrate a specific case. I suggest you create an example with your component in Planker and attach its link to this issue.

**Comment by Consi007** [comment]
Thanks.
