### ISSUE TITLE
Unexpected module 'DevExtremeModule' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by itszhangbo** [DevExpress/devextreme-angular2#119]

**Comment by stonecourier** [comment]
This sounds the same ad #114

**Comment by dxvladislavvolkov** [comment]
Hello!
We need more information to research the issue. Can you provide an example or a project where we can reproduce the problem?

**Comment by isaacplmann** [comment]
I reproduced this using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter).

1. `git clone https://github.com/AngularClass/angular2-webpack-starter.git`
2. `npm install --save devextreme-angular2`
3. Add `DevExtremeModule` to the imports in `AppModule` in `src/app/app.module.ts`
4. `npm run server:dev`

There's no AoT compilation happening in this workflow.

**Comment by isaacplmann** [comment]
One key difference, the error message I reproduced is `Unexpected module 'DevExtremeModule' imported by the module 'AppModule'`.  Note `imported`, not `declared`.  I assumed that the original poster just mistyped the error message.  If it isn't a typo, then the problem is that they're putting `DevExtremeModule` in the `declarations` section instead of the `imports` section.

**Comment by isaacplmann** [comment]
This happens when you upgrade to angular 2.0.1.  The problem goes away if you downgrade back to 2.0.0.

**Comment by isaacplmann** [comment]
And now, after wiping out node_modules and running `npm install` again, the problem has disappeared.  I'll post again if I can reliably reproduce.

**Comment by isaacplmann** [comment]
Ok. You can ignore my previous comment. I'm not sure what happened. Installing with Angular 2.0.1 reliably reproduces the issue.

**Comment by itszhangbo** [comment]
npm install devextreme-angular2  
![p1](https://cloud.githubusercontent.com/assets/20808570/18898418/1d4f0666-8564-11e6-9579-8e683ea88daf.png)

**Comment by itszhangbo** [comment]
![p2](https://cloud.githubusercontent.com/assets/20808570/18898492/8d467760-8564-11e6-9f47-e941c2cf1cdb.png)

**Comment by itszhangbo** [comment]
import { NgModule }      from '@angular/core';

import { BrowserModule } from '@angular/platform-browser';


import { AppComponent }  from './app.component';

app.module.ts

import { DevExtremeModule } from 'devextreme-angular2';

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ AppComponent,DevExtremeModule ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }

**Comment by itszhangbo** [comment]
thank you everyone for your answers. I found that this error is my fault,
right code is 
@NgModule({
    imports: [ DevExtremeModule],
    declarations: [
        AppComponent
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
my wrong code is 
@NgModule({
    imports: [ ],
    declarations: [
        AppComponent,DevExtremeModule
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
