### ISSUE TITLE
ReferenceError: DevExpress is not defined 

### ISSUE THREAD

**Issue by ybarbaria** [DevExpress/devextreme-angular2#12]
This error occured when I try to use your lib with angular2 in my project. 

> 
>  transacstandard:85 Error: ReferenceError: DevExpress is not defined
> 	    at Object.eval (http://localhost:5000/js/devextreme-angular2/core/dx.component.js:2:10)
> 	    at eval (http://localhost:5000/js/devextreme-angular2/core/dx.component.js:88:4)
> 	    at eval (http://localhost:5000/js/devextreme-angular2/core/dx.component.js:89:3)
> 	    at Object.eval (http://localhost:5000/js/devextreme-angular2/index.js:5:10)
> 	Evaluating http://localhost:5000/js/devextreme-angular2/core/dx.component.js
> 	Evaluating http://localhost:5000/js/devextreme-angular2/index.js
> 	Evaluating http://localhost:5000/app/components/devextreme/devextreme.js
> 	Evaluating http://localhost:5000/app/components/main/main.component.js
> 	Evaluating http://localhost:5000/app/boot.js
> 	Error loading http://localhost:5000/app/boot.js

I try to use devextreme like that in my system.config.js 

   ```
 // map tells the System loader where to look for things
    var map = {
        'app': 'app', // 'dist',
        'rxjs': 'js/rxjs',
        '@angular': 'js/@angular',
        'angular2-in-memory-web-api': 'js/angular2-in-memory-web-api',
        'ng2-bootstrap/ng2-bootstrap': 'js/',
        'moment': 'js/moment',
        'ng2-select': 'js/ng2-select',
        'ng2-bootstrap': 'js/ng2-bootstrap',
        'toastr': 'js/toastr.min.js',
        'devextreme-angular2':  'js/devextreme-angular2'
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'boot.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
        'angular2-cookie': { main: 'core.js', defaultExtension: 'js' },
        "moment": { defaultExtension: 'js' },
        'ng2-select': { defaultExtension: 'js' },
        'ng2-bootstrap': { defaultExtension: 'js' },
        'toastr': { defaultExtension: 'js' },
        'devextreme-angular2': { main: 'index.js', defaultExtension: 'js' } 
    };: 
```
 And I import the lib : 
`import {
    DxButton,
    DxCheckBox,
    DxSwitch,
    DxTextBox,
    DxTextBoxValueAccessor,
    DxTextArea,
    DxNumberBox,
    DxDateBox,
    DxProgressBar,
    DxSlider,
    DxRangeSlider,
    DxLoadIndicator,
    DxAutocomplete,
    DxSelectBox,
    DxTagBox,
    DxRadioGroup,
    DxColorBox,
    DxCalendar,
    DxTemplate,
    DxList,
    DxPopup,
    DxChart,
    DxDataGrid
} from 'devextreme-angular2';
`

**Comment by dxbykov** [comment]
Hi ybarbaria,

Please make sure you have a reference to the DevExtreme library that is required for Angular 2 integration in your index.html file.

It should look as follows:

```html
<script src="../node_modules/devextreme/dist/js/dx.all.js"></script>
```

**Comment by ybarbaria** [comment]
Hi dxbykov, 

Awesome, that's work !

Thx :)

**Comment by dxbykov** [comment]
You are welcome :)
