### ISSUE TITLE
Angular's Css separation methods don't work with dx-popup

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular2#124]
If you have the css in a seperate file for the component, it is not picked up if the component is enclosed in a popup (presumedly because it generates html outside of the component tag).

The only way I could get the css to work is have the css in the main file.

**Comment by dxvladislavvolkov** [comment]
Hello!
We have created an [example](http://plnkr.co/edit/XvaYjm?p=preview)
Please clarify what steps we should perform to reproduce the issue.

**Comment by stonecourier** [comment]
Sorry could not get plunker to run.

Attached a pdf with example and screenshots. The main thing is that adding a css class to the dx-popup itself does not work.

[Issue #124.pdf](https://github.com/DevExpress/devextreme-angular2/files/494061/Issue.124.pdf)

**Comment by dxvladislavvolkov** [comment]
You can try adding a css class to the dxTemplate order to use styles for the content.
As for the customization of dx-popup's styles, we will research this issue and let you know of our results.

**Comment by ovchinnikov** [comment]
Hello!
[Component styles](https://angular.io/docs/ts/latest/guide/component-styles.html) normally apply only to the HTML in the component's own template.
To allow external styles to affect the content of components you can use the _/deep/_ selector to force a style down through the child component tree into all the child component views.
You can see an example [here](http://plnkr.co/edit/s7lCfRtdNiJg6BEjMo0J?p=preview).
