### ISSUE TITLE
How to use Devexpress dialog methords in angular 2

### ISSUE THREAD

**Issue by sreejithsdev** [DevExpress/devextreme-angular2#125]
DevExpress dialog methods alert,notify,confirm,..etc not working in devextreme-angular2. 
Below code is not working for devextreme angular2 package.
DevExpress.ui.dialog.alert('Alert message', 'Alert title');

**Comment by dxvladislavvolkov** [comment]
Hello!
You can see an example [here](http://plnkr.co/edit/DGTf43?p=preview).

**Comment by sreejithsdev** [comment]
It works.Thank you..
