### ISSUE TITLE
Lookup columns in dx-data-grid

### ISSUE THREAD

**Issue by michaelwaihenya** [DevExpress/devextreme-angular2#126]
[T425099.zip](https://github.com/DevExpress/devextreme-angular2/files/495246/T425099.zip)

Specifying a grid column with lookup works when specified in html. However, when specified in component file, the values do not show. Note this happens when data is from a service. Hard coded array works.

**Comment by GoshaFighten** [comment]
@michaelwaihenya 
 
I just replied to you regarding this issue at [T431270](https://www.devexpress.com/Support/Center/Question/Details/T431270) in our Support Center. Please check out my answer.
