### ISSUE TITLE
Defining Widget Options In Code

### ISSUE THREAD

**Issue by hneuer** [DevExpress/devextreme-angular2#127]
Is it still possible like in Angular 1 to define the widget's options in code and then bind to the single option object?

Something along the line like:
`<div id="gridContainer" dx-data-grid="gridOptions"></div>`

**Comment by dxvladislavvolkov** [comment]
Hello!
You cannot do it this way. We use the Angular 2 syntax for specifying widget options.

**Comment by rafaelbiten** [comment]
Sorry for getting back to this but I'd like to confirm that this isn't really possible.

Something like this works:

```
<dx-chart
  [size]="overall.size"
  [series]="overall.series"
  [legend]="overall.legend"
  [dataSource]="overall.dataSource"
  [commonAxisSettings]="overall.commonAxisSettings"
  [commonSeriesSettings]="overall.commonSeriesSettings"
></dx-chart>
```

But it would be super nice if we could pass a single object of options instead, ie.:

```
<dx-chart [options]="overall"></dx-chart>
```

This chart won't ever need to be updated, so it should be fine if we pass properties this way.
