### ISSUE TITLE
dx-data-grid   angular2   onSelectionChanged

### ISSUE THREAD

**Issue by itszhangbo** [DevExpress/devextreme-angular2#128]
<dx-data-grid
            (onSelectionChanged)='helloWorld()'
            [columns]='[
                "CompanyName", 
                "City", 
                "State", 
                "Fax", 
                { 
                    dataField: "Phone", 
                    cellTemplate: "phoneCellTemplate" 
                }
            ]'
            [selection]='{
                mode:"single"
            }'
            [dataSource]='customers'
            [paging]='{
                pageSize: 10
            }'
            [pager]= '{
                showPageSizeSelector: true,
                allowedPageSizes: [5, 10, 20],
                showInfo: true
            }'>
        </dx-data-grid>

How to write Event SelectionChanged?  writed like my code Funciton can be triggered,but I can not know which row be clicked.

**Comment by dxvladislavvolkov** [comment]
To capture the event object, pass $event as a parameter in the function call.
Use the following code to fix the issue:
```html
 <dx-data-grid 
       [dataSource]="customers"
       (onSelectionChanged)="helloWorld($event)"
       [selection]="{
         mode: 'single'
       }"
   ></dx-data-grid>
```
```javascript
helloWorld(value) {
    console.log(value);
}
```

**Comment by itszhangbo** [comment]
thank you.
