### ISSUE TITLE
How to reset State in dx-pivot-grid?

### ISSUE THREAD

**Issue by sanket360** [DevExpress/devextreme-angular2#129]
I am using [stateStoring] like this-

```
<button (click)="Reset()">Reset State</button>

    <dx-pivot-grid style="width:600px;display:block" [(dataSource)]="pivotSource" [allowSorting]="true"
        [allowSortingBySummary]="true" [allowFiltering]="true" [allowExpandAll]="true"  [showBorders]="true"
        
        [fieldChooser]="{enabled: true}"
        [fieldPanel]="{visible: true}"
        [stateStoring]="{
            enabled: true,
            type: localStorage,
            storageKey: dx-widget-gallery-pivotgrid-storing
        }"
        >
    </dx-pivot-grid>
```

I want to know how to reset state on click on reset button in above snippet?

Also, Is there a way to store state other than localStorage type?

My Environment is-
Angular2 version RC5
devextreme-angular2 version: 16.1.5

**Comment by dxvladislavvolkov** [comment]
Hello!
You can read more about types of the storage [here](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxPivotGrid/Configuration/stateStoring/#type)

Try to use the following code to reset the state:

```javascript
import {Component, ViewChild} from '@angular/core';
import {DxPivotGrid} from 'devextreme-angular2'
...
export class App {
....
    @ViewChild(DxPivotGrid) pivotGrid: DxPivotGrid
    Reset() {
        this.pivotGrid.instance.getDataSource().state({});
    }
}
```

**Comment by sanket360** [comment]
Thanks @dxvladislavvolkov for quick response.

Any sample available for customSave and customLoad implementation?

**Comment by dxvladislavvolkov** [comment]
You can find some examples below:
[dxDataGrid does not restore its state when it is loaded manually via customLoad](https://www.devexpress.com/Support/Center/Question/Details/T254807)
[dxDataGrid - customLoad state storing example](https://www.devexpress.com/Support/Center/Question/Details/T223633)

**Comment by sanket360** [comment]
Thanks @dxvladislavvolkov but actually I am looking for angular2 samples.

**Comment by sanket360** [comment]
@dxvladislavvolkov Do you have sample for customSave and customLoad implementation in angular2?

**Comment by dxvladislavvolkov** [comment]
Hello!
You can see [the example](http://plnkr.co/edit/WC3LQr) where customSave and customLoad are used in angular 2.

**Comment by sanket360** [comment]
Thanks @dxvladislavvolkov :+1:
