### ISSUE TITLE
DxDataGrid Context Menu Not showing

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#13]
public onContextMenuPreparing(e: any) {
        if (e.target == 'content') {
            e.items = this.contextMenuItems;
        }
        return e;
    }

The event is called but the context menu doesn't show

**Comment by Angelminster** [comment]
It seems that the event 'onContextMenuPreparing' is called twice

Maybe related (still not working for me):
"Starting with version 16.1, handling of the dxcontextmenu event does not prevent the default browser behavior. This helps avoid issues that might occur when a browser doesn't react to user interactions as expected. You can manually suppress the execution of the default action as follows:

[JScript]
$(document).on("dxcontextmenu", function(e) {
    e.preventDefault();
}); "

**Comment by dxbykov** [comment]
I have reproduced the behavior and it looks to me as a bug. We need some time for further research.

**Comment by Angelminster** [comment]
Version 16.1.5 solves this issue.
