### ISSUE TITLE
Custom templates are not working if prod-mode is not activated

### ISSUE THREAD

**Issue by hneuer** [DevExpress/devextreme-angular2#130]
If the prod-mode is not activated and if custom templates are used Angular will throw the following exception:

`:8875/node_modules/@angular/core/bundles/core.umd.js:3462 EXCEPTION: Error in app/app.component.html:80:59 caused by: Expression has changed after it was checked. Previous value: 'CD_INIT_VALUE'. Current value: '
            Group Notebook
        '. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?`

The above error output is from the devextreme-angular2 examples with the prodmode deactivated in the main.ts file. This also results in the examples not being rendered correctly.

**Comment by dxbykov** [comment]
Hi,

Thank you for pointing this out. We are already aware of this issue and have a corresponding bug reported #4
