### ISSUE TITLE
DxPivotGrid & DxChart integration

### ISSUE THREAD

**Issue by sanket360** [DevExpress/devextreme-angular2#133]
I am trying to achieve DxPivotGrid & DxChart integration using below code snippet

**Template:**
```
    <dx-pivot-grid style="width:600px;display:block" [(dataSource)]="pivotSource" [allowSorting]="true"
        [allowSortingBySummary]="true" [allowFiltering]="true" [allowExpandAll]="true"  [showBorders]="true"
        [fieldChooser]="{enabled: true}"
        [fieldPanel]="{visible: true}"
onInitialized="pivotOnInitialized($event)">
    </dx-pivot-grid>

<dx-chart [commonSeriesSettings]="{type: bar}" [(dataSource)]="chart" onInitialized="chartOnInitialized($event)"></dx-chart>
```
**Component:**

```
constructor() {
        this.pivotSource =
        {
            store: {
                type: "xmla",
                url: "http://XXXXXXX/olap/msmdpump.dll",
                catalog: "XXXXXXXX",
                cube: "XXXXXXXX"
            }
        }
        
        
    }

chartOnInitialized($target) {
       this.chart = $target.component;
    }

    pivotOnInitialized($target) {
        $target.component.bindChart(this.chart, {
                dataFieldsDisplayMode: "splitPanes",
                alternateDataFields: false
            });
    }
```
My PivotGrid is working fine. But, I do see below error in browser console and Chart control is empty.
```
dx.all.js:9 E2001 - Invalid data source. See:
http://js.devexpress.com/error/16_1/E2001
```

Could you please guide me on this - how to achieve DxPivotGrid & DxChart integration?

My Environment is-
Angular2 version RC5
devextreme-angular2 version: 16.1.5

**Comment by GoshaFighten** [comment]
At the moment, there is a problem that the onInitialized event is not raised. See #14 . To implement chart integration in the pivot grid, use my sample from the [How to implement dxChart with dxPivotGrid integration in Angular 2](https://www.devexpress.com/Support/Center/Question/Details/T430051) ticket.

**Comment by sanket360** [comment]
Thanks @GoshaFighten  for quick response.
I used `(onContentReady)="pivotGridInitialized()"` and I can see line chart.
Can you tell me which types of charts it will support for this integration? any reference link?

**Comment by GoshaFighten** [comment]
This error usually occurs if dxChart does not have a data source. So, I think your `chart` property is null at the moment the chart is initialized. I suggest you set the default value of this property to an empty array. This should resolve the issue.

`
chart = [];
`

The `bindChart` method accepts only a dxChart instance. See the [bindChart(chart, integrationOptions)](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxPivotGrid/Methods/#bindChartchart_integrationOptions) help topic.

**Comment by sanket360** [comment]
Thanks @GoshaFighten for your help. :+1:
