### ISSUE TITLE
DxPivotGrid - showing fieldChooser next to grid instead of popup

### ISSUE THREAD

**Issue by sanket360** [DevExpress/devextreme-angular2#136]
I am using dx-pivot-grid like this-

```
    <dx-pivot-grid style="width:600px;display:block" [(dataSource)]="pivotSource" [allowSorting]="true"
        [allowSortingBySummary]="true" [allowFiltering]="true" [allowExpandAll]="true"  [showBorders]="true"
        [fieldChooser]="{enabled: true}"
        [fieldPanel]="{visible: true}"
        >
    </dx-pivot-grid>
```

In this fieldChooser available as popup. Is there a way to show fieldChooser next to Pivot Grid just like excel pivot?

My Environment is-
Angular2 version RC5
devextreme-angular2 version: 16.1.5

**Comment by sanket360** [comment]
Is this option available? If yes then please share some sample/references.

**Comment by Angelminster** [comment]
Hi,

[Documentation](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxPivotGridFieldChooser/)

"The field chooser is already integrated in dxPivotGrid and can be invoked using the context menu. If you need to continuously display the field chooser near the dxPivotGrid widget, use the dxPivotGridFieldChooser widget."

Regards

**Comment by sanket360** [comment]
Thanks @Angelminster :+1:
