### ISSUE TITLE
DxResponsiveBox - important events don't work

### ISSUE THREAD

**Issue by dxvladislavvolkov** [DevExpress/devextreme-angular2#137]
See an example [here](http://plnkr.co/edit/OCbJWj?p=preview)

**Comment by hneuer** [comment]
Is it possible that this affects other widgets/events too?
I noticed that the 'initialized' event of a dxList does not seem to fire (the 'itemClick' event on the same list works fine).

**Comment by dxbykov** [comment]
Hi,

The issue with the 'initialized' event was fixed in the context of #14. It will be available with the next devextreme-angular2 npm package update.

**Comment by dxbykov** [comment]
It appears that the 'onItemClick' event issue is not related to the Angular 2 integration. I have created a  [corresponding ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T439295) in our Support Center.
