### ISSUE TITLE
width property of  DxPivotGrid doesn't work,

### ISSUE THREAD

**Issue by itszhangbo** [DevExpress/devextreme-angular2#144]
<dx-pivot-grid style="height:365px; max-width:750px;width:750px" [(dataSource)]='geographyStore'
        [allowExpandAll]="true"
        [scrolling]='{
           mode:"standard",useNative:true
        }'
        [export]= '{
        enabled: true,
        fileName: "Sales"
        }'
        [width]='300'
        [height]="500"
        [allowSorting] = "true"
        [allowSortingBySummary] = "true"
        [allowFiltering] = "true"
        [allowExpandAll] = "true"
        [showBorders] = "true"
        [fieldChooser] = "{enabled: true}"
        >
    </dx-pivot-grid>
neither  style="height:365px; max-width:750px;width:750px"   nor  [width]='300'  work

**Comment by itszhangbo** [comment]
![pt](https://cloud.githubusercontent.com/assets/20808570/19217906/14695f82-8e1b-11e6-81b2-86a48efb17d7.png)

**Comment by Aden-git** [comment]
Hello,

It's may be related with #45. Try to add the following style:
```dx-pivot-grid { display: block; }```

**Comment by itszhangbo** [comment]
thank you
