### ISSUE TITLE
dx-chart: clipping does not work if a base tag is defined in index.html <base href="/">

### ISSUE THREAD

**Issue by mgeramb** [DevExpress/devextreme-angular2#145]
The lines of the charts are drawn over the axis if the user uses the zoom. I found that the generated svg code does not work with the <base href="/"> tag, which is very common for angular2 apps. For me, I found a workaround: I removed the base tag and added the base instead as provider (see [APP_BASE_HREF](https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html))

Here is an example of the code which is generated by an dx-Chart. (If you remove the base tag, the clipping will work correct)
[sampleHTML.txt](https://github.com/DevExpress/devextreme-angular2/files/521323/sampleHTML.txt)

**Comment by Angelminster** [comment]
¿#67?

**Comment by pavelgruba** [comment]
If a web page has a BASE tag, the [pathModified](https://js.devexpress.com/Documentation/16_1/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/#pathModified) option should be set to true. In that case, the chart should be rendered correctly in all web browsers. Note that the URL resolve was changed somehow in the latest Chrome (54), so the chart is rendered just fine without the pathModified option.
This change in Chrome also fixes the issue described in #67.
