### ISSUE TITLE
dxScrollViews height-property is broken

### ISSUE THREAD

**Issue by strpipe** [DevExpress/devextreme-angular2#146]
Though one can set the height property to a number. This means that `[height]=200`  and `[height]="200"` will work but `[height]="200px"` will throw an error. 

I encountered this problem because I wanted to assign a relative height-property to it, meaning something like: `[height]="100%"`. I am not sure if this will work, because I can also set these styles with inline-css  and something like `sytles="display: block; height: 100%; ` does not do the trick.

I will look further into this.
Maybe you can also help me out with it. I basically want a dxPopUp with relative height showing scrollable content.

Thank you!

**Comment by hneuer** [comment]
Have you tried [height]="'100%'"?

**Comment by strpipe** [comment]
Yes, did it work for you?

**Comment by Aden-git** [comment]
Hello,

If the approach above did not yet help you, I suggest that you try out [this example](http://plnkr.co/edit/oExMXqPqPu3r9OAV4Mm4?p=preview).

**Comment by strpipe** [comment]
Thank you,
#168 turned out to solve my specific problem
