### ISSUE TITLE
lookup feature in data grid

### ISSUE THREAD

**Issue by sherry9872** [DevExpress/devextreme-angular2#156]
Can we set up lookup feature with all the values of a column present in the grid and not have a separate master table for the same? As displayed in demo [https://js.devexpress.com/Demos/WidgetsGallery/#demo/data_grid-editing-cell_editing_and_editing_api](url)

basically I need auto complete for all text fields withing the grid. Can this feature be achieved?

**Comment by anna-zhernovkova** [comment]
Hello!

You can use an [example](http://plnkr.co/edit/Co8sLR?p=preview) for this functionality.
If you will have some question, please fill free to contact me

**Comment by anna-zhernovkova** [comment]
Hello!

You can see an [example](http://plnkr.co/edit/Co8sLR?p=preview) for this case. Should you have any further questions, feel free to contact us.

**Comment by sherry9872** [comment]
Thanks for the update. The scenario that I have does not have a separate state variable to bind as auto complete lookup. For example in the provided plunker if I only have the employees data and nothing else. Do we have feature where we can read the sate value from the employee variable only and create auto filled options?  In my scenario I don't have a separate variable with all the autocomplete options. Can we still achieve the same functionality then.,

**Comment by anna-zhernovkova** [comment]
DxDataGrid doesn't have a built-in method for this case. To solve this issue, you can use the following code (with a value from the previous example for the 'Position' column):
```
{
    dataField: 'Position',
    width: 170,
    lookup: {
        dataSource: dataSource,
        displayExpr: 'Position',
        valueExpr: 'Position'
    }
}
```
Please let us know if it is what you are looking for.
