### ISSUE TITLE
Can you make three state switch box ?

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular2#157]

**Comment by anna-zhernovkova** [comment]
Hello!
The DxSwitch supports only two states: the "value" option can be only "on" or "off". But we have a [DxCheckBox](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxCheckBox/Configuration/#value), which can have three states, and it can meet your requirements.
Please let us know if it is what you are looking for.

**Comment by Consi007** [comment]
we want to three state switch box. Our developer don't like check box's shape .

**Comment by anna-zhernovkova** [comment]
Thank you for sharing your ideas. I have informed our developers about your suggestion. They will take it into account.

**Comment by Consi007** [comment]
Thanks.
