### ISSUE TITLE
customizeText in summary gridView

### ISSUE THREAD

**Issue by GhEllie** [DevExpress/devextreme-angular2#158]
I am using DevExpress gridView and i need to customize  avg to show only decimal 2 .
 I find that it is possible using js like bellow :
{
            column: "OrderDate",
            summaryType: "min",
            customizeText: function(data) {
                return "First: " + Globalize.formatDate(data.value, { date: "medium" });
            }

but I am html for defining templates and grid using  <dx-data-grid/> tag .
How can I customize avg value in html ?
Thanks

**Comment by anna-zhernovkova** [comment]
Hello!
You can use the '[valueFormat](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/summary/groupItems/#valueFormat)' option instead of the 'customizeText', for example:

```
[summary]="{
    totalItems: [{
        column: 'SaleAmount',
        showInColumn: 'SaleAmount',
        displayFormat: 'Average: {0}',
        valueFormat: {
            type: 'decimal',
            precision: 2
        },
        summaryType: 'avg'
    }]
}"
```

Should you have any further questions, feel free to contact us.

**Comment by GhEllie** [comment]
It works fine .

Thanks for your complete answer.

**Comment by anna-zhernovkova** [comment]
You are welcome. Feel free to contact us.
