### ISSUE TITLE
Utilize DevExtreme modules for a better application build experience

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/devextreme-angular2#16]
Now the DevExtreme bundles are used and don't allow taking all possible advantages of using WebPack and other build tools.

**Comment by Angelminster** [comment]
Hi,

Is devextreme-angular2 prepare to WebPack? 
I've created a simple bundle of my app and all works except devextreme-angular2 components. It seems that throws "No Directive annotation found on X" X = DxButton, DxPopup, etc. 

Thank You

**Comment by dxbykov** [comment]
Hi,

It should work. We need some time to check this if you still haven't managed to make it work.

**Comment by Angelminster** [comment]
It works!

**Comment by kvet** [comment]
Implemented in #154
