### ISSUE TITLE
dx-toast is not working correctly

### ISSUE THREAD

**Issue by sherry9872** [DevExpress/devextreme-angular2#160]
Please look into the dx-toast feature. #

**Comment by anna-zhernovkova** [comment]
Hello!
I do not quite understand what you mean. I've prepared a simple [example](http://plnkr.co/edit/5MyyvuFrg7ePxBUmJ08o?p=preview) illustrating how you can use the DxToast. Let us know if this helps you.

**Comment by sherry9872** [comment]
Hi,
In the example shared by you, the custom toast is not working.

**Comment by anna-zhernovkova** [comment]
I apologize, it was my mistake. The sample had a small issue in the styles. I have fixed it. Please try the example now.

**Comment by ErBhautik** [comment]
custom dx-toast is not working correctly
