### ISSUE TITLE
npm package.json: main pointing to index.ts

### ISSUE THREAD

**Issue by hneuer** [DevExpress/devextreme-angular2#162]
Hy!

In the package.json downloaded from npm the "main" property points to the non-existing "./index.ts" which results in an error when trying to get the package using systemjs.

I think this should be set to "./index.js".

**Comment by dxbykov** [comment]
Hi,

The index.ts file is generated during the build process. You can generate it as follows:

```bash
npm run build
```

**Comment by hneuer** [comment]
Thanks for the quick response!

Some more information: I am using a setup according to https://github.com/mgechev/angular-seed where dependencies are injected from npm in the following way:

`this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'cldrjs/dist/cldr.js', inject: 'libs'},
      {src: 'cldrjs/dist/cldr/event.js', inject: 'libs'},
      {src: 'cldrjs/dist/cldr/supplemental.js', inject: 'libs'},
      {src: 'globalize/dist/globalize.js', inject: 'libs'},
      {src: 'globalize/dist/globalize/message.js', inject: 'libs'},
      {src: 'globalize/dist/globalize/number.js', inject: 'libs'},
      {src: 'globalize/dist/globalize/currency.js', inject: 'libs'},
      {src: 'globalize/dist/globalize/date.js', inject: 'libs'},
      {src: 'jszip/dist/jszip.min.js', inject: 'libs'},
      {src: 'reflect-metadata/Reflect.js', inject: 'libs'},
      {src: 'devextreme/dist/js/dx.all.js', inject: 'libs'}
    ];`

systemjs then tries to get download http://localhost:5555/node_modules/devextreme-angular2/index.ts.js (which it can not find). 

Changing the index.ts to index.js in package.json fixes this for me (but this changes will be deleted on the next 'npm install').

 I really think this is a bug. I checked some package.json files from other libs and 'main' seems always to point to an existing file in the package.
