### ISSUE TITLE
How to consume data from webapi (json format) into DxPivotGrid in angular2?

### ISSUE THREAD

**Issue by sanket360** [DevExpress/devextreme-angular2#164]
How to consume data from webapi (json format) into DxPivotGrid in angular2?

I tried like this-

```
this.pivotSource =
        {
            store: {
                type: "json",
                url: "http://localhost:51115/api/Testing1",
            }
        }
```

This gives me error saying invalid type.

> Error: E4020 - Unknown store type is detected: json. See:
> http://js.devexpress.com/error/16_1/E4020

If i look into documentation of store type
(https://js.devexpress.com/Documentation/16_1/ApiReference/Data_Layer/DataSource/Configuration/store/#type),
I did not see any json type. Which type should I use incase of webapi?

**Comment by sanket360** [comment]
If I use dxPivotGrid in ASP.NET core, I am able to read data like below with one line of code. 
`.Store(s => s.WebApi().Controller("Testing1"))`

But I am looking to achieve this in angular2 version of DxPivotGrid  

```
@(Html.DevExtreme().PivotGrid()
        .Height(500)
        .AllowExpandAll(true)
        .AllowSorting(true)
        .AllowSortingBySummary(true)
        .AllowFiltering(true)
        .DataSource(d => d
            .Store(s => s.WebApi().Controller("Testing1"))
        )
        .FieldChooser(f => f.Layout(PivotGridFieldChooserLayout.Layout0))
        .Scrolling(s => s.Mode(PivotGridScrollingMode.Standard))
        .FieldPanel(p => p.Visible(true).ShowFilterFields(false))
```

**Comment by GoshaFighten** [comment]
@sanket360 
Our stores can't work with JSON returned from a controller. Our wrappers use a special helper class from [https://github.com/DevExpress/DevExtreme.AspNet.Data](https://github.com/DevExpress/DevExtreme.AspNet.Data) to work a controller actions. You can use this class in your project. To install it, you can use Bower. Add the following dependency to the `bower.json` file:

`
"devextreme-aspnet-data": "1.0.0"
`

Then, restore Bower packages and reference `bower_components/devextreme-aspnet-data/js/dx.aspnet.data.js` on the index.html page after the `dx.all.js` file.

Then, you can create a DxPivotGrid data source like:

`
pivotStore = DevExpress.data.AspNet.createStore({ "loadUrl": "/Detail/Get", });
`
I've attached a sample project to illustrate this.
[WebApplication1.zip](https://github.com/DevExpress/devextreme-angular2/files/541711/WebApplication1.zip)

**Comment by sanket360** [comment]
Thanks @GoshaFighten :+1:  
With this createStore approach I am able to get data into PivotGrid.

However, I do have couple of small questions-
1. Does this devextreme-aspnet-data package available on npm? similar to devextreme-angular2.
2. Is there a way to pass parameter in GET url? Any documentation available for this?

**Comment by GoshaFighten** [comment]
You are welcome, @sanket360 
Since the additional questions don't relate to our Angular 2 support, would you please re-post them in our [https://github.com/DevExpress/DevExtreme.AspNet.Data](https://github.com/DevExpress/DevExtreme.AspNet.Data) repository which is dedicated to the ASP.NET.Data library?

**Comment by sanket360** [comment]
Sure @GoshaFighten
