### ISSUE TITLE
DxDataGrid CellTemplate

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#17]
How can i use DxTemplate to customize cellTemplate in dxDataGrid?

**Before**:
```
<div data-options="dxTemplate:{ name:'buttonDeleteCellTemplate' }">
    <div dx-button="{bindingOptions: {onClick: 'vm.buttonClicked'}, 'text': 'Delete'}"></div>
</div>
```
in Column:
 { dataField: 'whatever', dataType: 'string', caption: 'superCaption' cellTemplate: 'buttonDeleteCellTemplate'  }
     
**Now?**

**Comment by dxbykov** [comment]
Hi,

Thank you for pointing out this case. It appears to be a bug. We suppose it should work as follows:

```html
    <div *dxTemplate="let cellData = data of 'buttonDeleteCellTemplate'">
        <div dx-button onClick="buttonClicked" text="Delete"></div>
    </div>
```

**Comment by staran** [comment]
Hi, so am I getting this right, are cellTemplates currently not working with devextreme-angular2 in dx-data-grid?

**Comment by dxbykov** [comment]
Hi staran,

You are right. We'll fix this issue and publish an update soon.
