### ISSUE TITLE
clearFilter doesn not clear the search panel in gridView

### ISSUE THREAD

**Issue by GhEllie** [DevExpress/devextreme-angular2#172]
I tried to clear gird using clearFilter()  method .
It clears all the filters of a specific type applied to grid records but does not clear the search panel .

You can see the bug in the below page as well:
https://js.devexpress.com/Demos/WidgetsGallery/#demo/data_grid-filtering_and_sorting-filtering

many thanks

**Comment by anna-zhernovkova** [comment]
Hello,
It looks like this issue is not related to the devextreme-angular 2 integration. Please redirect your question to our [DevExpress Support Center](https://www.devexpress.com/Support/Center/).

**Comment by GhEllie** [comment]
Could you please clarify, whether the limitation is with Angular 2 wrapper code (available here) around the underlying javascript grid api or is this a limitation in the javascript grid or api?

**Comment by anna-zhernovkova** [comment]
Since the issue can be reproduced without devextreme-angular 2 integration, it is related only to our DevExtreme project.

**Comment by GhEllie** [comment]
Thanks 
I will redirect my question to DevExpress support  team .
