### ISSUE TITLE
virtual scrolling does not work in gridView

### ISSUE THREAD

**Issue by GhEllie** [DevExpress/devextreme-angular2#174]
I use the below setting in my gridview;

 [scrolling]="{
            mode: 'virtual',
                  }"
 [paging]="{
            pageSize: 10
        }"

for scrolling and i have a bout 500 records in my grid . I would like to see records when i scroll down the grid but grid shows only the first 50 records by scrolling .
The length of scroll seems fine and i can scroll by the end of grid but it doesn't show any data after the 50th record.

**Comment by GhEllie** [comment]
I also tried that using FireFox and I saw that in fireFox it is loading 120 records and in chrome it is showing only 50 records .

I am using the latest version of chrome and firefox .

**Comment by anna-zhernovkova** [comment]
Hello!
 
I created a [simple application](http://plnkr.co/edit/nLj2HYzaBEkzhmNC0yoQ?p=preview) but wasn't able to reproduce the issue. I tested it in Google Chrome version 54.0.2840.71 m. Would you please check it on your side and let me know what details are missing? 
If possible, modify my example and send it back to us for further research.

**Comment by GhEllie** [comment]
Thanks for your sample.
I think something is wrong with grid height because without setting height  to a fix value , my grid won't show more than 50 records but when i set height for grid (using style) virtual scrolling works fine .

I even try to set height using height property but It did not apply height to the grid.Only using styling I can fix height .

**Comment by anna-zhernovkova** [comment]
I modified the sample - you can see how to set the height via the component property. 

Try setting "display: block;" in styles, this should help you address the issue. We had the [issue](https://github.com/DevExpress/devextreme-angular2/issues/45) which was fixed in DevExtreme 16.2-alpha.1

**Comment by GhEllie** [comment]
Yes after setting display: block and a fixed height  it works fine but Isn't it an issue that you have to set display: block and a fixed height to make grid works fine ?

Anyway thanks for your response it solved my problem .

**Comment by anna-zhernovkova** [comment]
This issue was fixed in DevExtreme 16.2-alpha.1
