### ISSUE TITLE
datagrid Export to Excel using a customize button 

### ISSUE THREAD

**Issue by GhEllie** [DevExpress/devextreme-angular2#184]
I am using  devextreme-angular2@16.1.7-alpha
I would like  to export grid data into an Excel file. It exported data to excel file successfuly but I do not like to have a button at the top of grid , instead I want to export data using a custom button .

Could you please guide me if the library provides this or not ?

Many Thanks

**Comment by anna-zhernovkova** [comment]
Hello!
You can use the [exportToExcel](https://js.devexpress.com/Documentation/16_1/ApiReference/UI_Widgets/dxDataGrid/Methods/#exportToExcelselectionOnly) method to create a custom export button. 
Should you have any further questions, feel free to contact us.

**Comment by GhEllie** [comment]
Thanks .it works  for me
