### ISSUE TITLE
DxPopUp not transcluding content

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#19]
If i try this:
```
<dx-popup [visible]="true" [title]="'SuperTitle'">
    HELLO
</dx-popup>
```
It shows the popup with the title but doesn't show "Hello" in the content.

If I try to use it with Templates:
```
<dx-popup [visible]="true" [title]="'SuperTitle'">
    <div *dxTemplate="let data = data of 'contentTemplate'">
        Hello
    </div>
</dx-popup>
```
It doesn't show anything

**Comment by Angelminster** [comment]
Same problem with dxToolTip

**Comment by dxbykov** [comment]
I've just pasted your code sample with a template (the second one) on our [sample page](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html),  and it works properly on my side. 

Would you please check if this code from our examples works on your side:

```html
    <dx-popup [showTitle]="true" title="Demo of dxPopup" [(visible)]="popupVisible">
        <div *dxTemplate="let t = data of 'contentTemplate'">
            <div>Hello from dxPopup</div>
        </div>
    </dx-popup>

    <dx-button text="Show Popup" (onClick)="popupVisible = !popupVisible"></dx-button>
```

**Comment by Angelminster** [comment]
Ok, Thank You. It Works

The problem was setting [visible]="true" without binding to a variable and changing it.

**Comment by jandresampaio** [comment]
Is it working now? I've just pasted this example and it's not showing any content.

**Comment by luigidallavalle** [comment]
> The problem was setting [visible]="true" without binding to a variable and changing it.

Why is not possible to set it directly to true? I have a set of dynamically generated images, each one of them needs a tooltip, am I supposed to create an array of boolean to be bound to the visible property?
