### ISSUE TITLE
DxNumberBox - editor does not take values from ReactiveForms FormControl

### ISSUE THREAD

**Issue by rstabenow** [DevExpress/devextreme-angular2#194]
Version 16.2.1-alpha.1 (also 16.1.7)

The editor of the DxNumberBoxComponent won't show inital values from the FormControl (showing always 0) or reflect changes made to that value.

http://plnkr.co/edit/0UQOPF3lyincq1mNpW7w?p=preview

**Comment by kvet** [comment]
Hi,
 
The issue is related to problem #6, and the fix will be available in `16.2-alpha.2`.
