### ISSUE TITLE
OverlayContent Cannot be dragged

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#20]
I cant move popup Windows like columnChooser or DxPopUp.

With Devextreme 15.* i had the same problem in columnChooser. Maybe it's a bug not related to devextreme-angular2.

Thank you.

**Comment by Aden-git** [comment]
Hi,

I tried to move DxPopUp and DxDataGrid columns on a [sample page](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html). To drag columns in DxDataGrid, I have added the following HTML: 

`[columnChooser] = '{ enabled: true, mode: "selectedMode" }'`

On my side, it all works fine. Can you please specify steps I need to do to reproduce this issue?

**Comment by Angelminster** [comment]
Hi,

I can Drag & Drop columns in ColumnChooser and in Group panel too. My problem is about moving the popup window itself (ColumnChooser, FieldChooser, Custom dxPopUp, whatever). Maybe i have some css that could restrict the movement, but i cant found it.¿Some ideas?

The steps to reproduce are simple:
1. Open columnChooser of dxDataGrid
2. Try to Move the popup window dragging the header. -> The icon changes properly (movement cross) but I can't move it.

I've have a complex solution and could be a lot of things ( css problem, ng-trasclude, incompatibility with another components, etc,) I'll try to create a simple case to reproduce this.

**Comment by Angelminster** [comment]
In this [fiddle](https://jsfiddle.net/z6f5g589/1/) if you add "columnChooser: {enabled: true}" in line 99 you get the same behaviour. You can't move the columnchooser.

[Here](http://js.devexpress.com/Demos/WidgetsGallery/#demo/data_grid-columns-column_customization ) the expected result.

**Comment by Aden-git** [comment]
It seems it's not related to devextreme-angular2.
If you wish to discuss technical issues related to DevExtreme components, please submit a ticket in our [Support Center](https://www.devexpress.com/support/center). Our support engineers will help you.

As for your [example](https://jsfiddle.net/z6f5g589/1/), try to add the following CSS:

`html, body{
  height: 100%;
  width: 100%;
}`

**Comment by Angelminster** [comment]
Thank You so much Aden. That  css rule solves the problem.
