### ISSUE TITLE
Unsupported number of argument for pure functions: 11

### ISSUE THREAD

**Issue by ybarbaria** [DevExpress/devextreme-angular2#22]
Hello,

When I configure more than 10 columns for "dx-data-grid", this error appear : 

> Uncaught (in promise): Unsupported number of argument for pure functions: 11

> zone.js:461 Unhandled Promise rejection: Unsupported number of argument for pure functions: 11 ; Zone: angular ; Task: Promise.then ; Value: BaseException {message: "Unsupported number of argument for pure functions: 11", stack: "Error: Unsupported number of argument for pure fun…ty_binder.js:168:9)↵    at Array.forEach (native)"}

Thx

**Comment by dxbykov** [comment]
A similar issue is discussed [here](http://stackoverflow.com/questions/37113385/unsupported-number-of-argument-for-pure-functions). It seems to be a limitation of Angular 2. Please make sure it's not possible to move dxDataGrid columns declaration from markup to its parent component property as described in the mentioned thread.

**Comment by ybarbaria** [comment]
I saw this solution before post here my bug, I will try soon.

**Comment by ybarbaria** [comment]
@dxbykov  it works !

**Comment by dxbykov** [comment]
Hi ybarbaria,

Nice to hear that. Thank you for checking this out. I'm closing this thread.

**Comment by Jlamb25** [comment]
Hi, 
Would you mind sharing how you managed to move the column definitions from the markup into the parent component property?

**Comment by ybarbaria** [comment]
Hey, 

For sure, no worries. 

```
   <dx-data-grid style="height: auto; width: 100%; display: block"
                              [columns]='tbDataColumns'
                              [dataSource]='dataTransacExtrem'
                              [paging]='{
                                    pageSize: 10
                                    }'
                              [pager]='{
                                    showNavigationButtons: true
                                    }'
                              [editing]='{
                                    mode: "batch",
                                    allowUpdating: true,
                                    allowAdding: true,
                                    allowDeleting: true
                                    }'
                              [cacheEnabled]="true"
                              [allowColumnReordering]="true"
                              [filterRow]="{
                                    visible: true
                              }"
                              [export]="{
                                    enabled: true,
                                    fileName: 'Transac',
                                    allowExportSelectedData: true
                              }"
                              [allowColumnResizing]="true"
                              [searchPanel]='{
                                    visible: true,
                                    width: 240,
                                    placeholder: "Search..."
                              }'>

                </dx-data-grid>
```


my .ts content : 

` tbDataColumns = [
        'reportingstate',
        'correlationid',
        'entity',
        'counterpart',
        'trader',
        'agression',
        'direction',
        'transactionDate',
        'executionDate',
        'uniqueTransactionId',
        'linkedTransactionId',
        'terminaisonDate',
        'time',
        'actiontype',
        'onvoice',
        'tradingcapacity',
        'capturedate',
        'lastaction',
        'contractid',
        'contractname',
        'contractype',
        'material',
        'indexname',
        'marketplace',
        'settlement',
        'lasttradingtime',
        'gripoints',
        'countryMapped',
        'time',
        'id'
    ];`

**Comment by Jlamb25** [comment]
Brilliant, 
Thanks Yvan
