### ISSUE TITLE
DxMap Initialization

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#28]
Is this component ready?
I get an exception: "zone.js:260 Uncaught RangeError: Maximum call stack size exceeded"

DxVectorMap is working as expected.

**Comment by Aden-git** [comment]
Hi,
I've tried to reproduce the issue on a [sample page](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html), but it works fine except for one thing: the DxMap component should have the `display: block;` style (we will fix it as soon as possible).
 
Could you please provide us with any additional information related to this issue?

**Comment by Angelminster** [comment]
Hi,
With display:block works for bing map, google in normal situation. 

When i set the provider google and add markers with location 'string'  shows the error. Actually it only throw exception when the string location isn't as good as it should be. For instance without country. If i set location with latitude and longitude, it works. My markers fails even only with location. (not title, onClick event or tooltip)

I can't get it working with 'googleStatic'

Example Markers:
```
        this.markers = [
            {
                location: 'Calle Mayor 10, Madrid',//, España',
            },
            {
                location: 'Paseo Castellana 12, Madrid,'//, España',
            },
            {
                location: 'Calle Antracita 2, Madrid',//, España ',
            }
        ];
```

If you uncomment country "España". it works as expected.

**Comment by Angelminster** [comment]
Sorry, i had a problem with my key in googleStatic. It works too.

The only issue is the one related to markers.

Thank You

**Comment by Aden-git** [comment]
I tried to reproduce the issue with markers in [Widget Gallery Demo](http://js.devexpress.com/Demos/WidgetsGallery/#demo/maps-map-markers) without devextreme-angular2 integration, and it's does not work properly too. 
To determine the cause of this behavior, please submit a ticket in our [Support Center](https://www.devexpress.com/support/center). Our support engineers will help you.

**Comment by Angelminster** [comment]
I've done it. I gonna close this ticket.
