### ISSUE TITLE
DxValidator Message Transclusion and *ngIf

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#29]
Hi,

This is a though one.

If you have a componentA with transclusion like this:
```
<div *ngIf="dataSource"> 
    <ng-content></ng-content>
</div>
```
And in a componentB:
```
<componentA>
    <dx-text-box [(value)]="datafield" [IsValid]="whatever" [validationError]="{ message: 'Invalid'}"></dx-text-box>  
</componentA> 
```
When **dataSource** is null first and then it gets a value. With this circunstances the dxValidator doesn't show Properly. The problem is the `<div *ngIf="**dataSource**">` and Transclusion together.

An easy work around is changing de *ngIf to the child and it works:

```
    <ng-content></ng-content>
```
And in a componentB:
```
<componentA>
    <dx-text-box *ngIf="dataSource" [(value)]="datafield" [validationError]="{ message: 'Invalido'}"></dx-text-box>  
</componentA> 
```

Thank You.

**Comment by dxbykov** [comment]
Hi,

We couldn't reproduce the issue on our side using your code snippets. Would you please provide us with a working sample demonstrating the issue?

**Comment by Angelminster** [comment]
This issue doesn't seem to be related to devexpress-angular2 components.
