### ISSUE TITLE
DxValidator with validationRules

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#30]
Hi,

Before devextreme-angular2 i can automatically configure the adapter for the dxValidator like this

```html
<div data-ng-model="vm.data" dx-text-area="{...}" dx-validator="vm.validationrules">
```

Now i can use Custom Validation Engine with [isValid] and [validationError] and works as you showed in the example. 

The problem is that I already have a lot of validationRules defined in my app ->validationrules = { validationRules: [{ type: "required" }] };
Is there a simple way to associate the validationRules to the editor? [validationRules]="validationrules"?
Is there a way to associate an Editor with a DxValidator?  [validator]="validatorRef/instance/etc"? Transclusion maybe?
If the proper way is to configure the adapter manually, can you provide an example? 

Thank You so much.

**Comment by marcelgood** [comment]
Having the same issue/question. I tried the following, but that doesn't seem to do anything.

`<dx-text-box [(value)]="model.reportNumber" [dx-validator]="{ validationRules: [{ type: 'required', message: 'Report number is required.' }] }"></dx-text-box>`

**Comment by dxbykov** [comment]
Thank you for your cases. We need to check if we can make dx-validator work as an Angular 2 directive, not a component. 

As a workaround, please check if the [Angular 2 forms and validators](https://github.com/DevExpress/devextreme-angular2#angular-2-forms) are suitable for you.

**Comment by marcelgood** [comment]
Yes, I was able to do what I need to using isValid and validationError bindings. However, I would also like to use the DxValidationSummary component, but it doesn't seem to work, either. I placed it in my HTML like so, but it doesn't display anything:

`<dx-validation-summary></dx-validation-summary>`
