### ISSUE TITLE
Can't use full width for my charts

### ISSUE THREAD

**Issue by ybarbaria** [DevExpress/devextreme-angular2#32]
I try to use the 100% width of my screen but the chart are created at rectangle with width of 400 px. 
I have try class "full-width" without succes.
I have try to fix the parent container size and set the child chart at auto or pourcentage without succes. 
Have you a solution for fix it? 
Thx 
YB

**Comment by Aden-git** [comment]
Hello,

Custom tags has a `display: inline;` by default, and not all of our widgets have any display style by default. It can be the cause of this behavior. Try to add a `display: block;`.

> I have try class "full-width" without succes.
 
If you mean "full-width" class in our demo, note that this class declared only in our demo, and contains following css:
`.full-width {
            width: 100%;
            display: block;
}`

If this does not help you, please provide us a sample.

**Comment by ybarbaria** [comment]
Works perfectly !  

Thx

**Comment by dxbykov** [comment]
You are welcome!
