### ISSUE TITLE
DxScheduler FirstDayOfWeek Problem

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#33]
Hi,

Setting FirstDayOfWeek in DxScheduler sets the days wrong. In the sample page it works: [DxScheduler](http://js.devexpress.com/Demos/WidgetsGallery/#demo/forms_and_multi-purpose-scheduler-overview)

![dxscheduler problem](https://cloud.githubusercontent.com/assets/18451577/16618428/944c092a-4389-11e6-801f-0cfb4b2632b7.png)

Thank You

**Comment by Aden-git** [comment]
Hello,
 
I tried to reproduce this issue, but on my side this option works as expected. Could you provide some more details about it or a code sample?
 
![2016-07-07_1604](https://cloud.githubusercontent.com/assets/11654514/16654054/a60ad9d8-445c-11e6-8c41-6bfc6ac1cd56.png)

**Comment by Angelminster** [comment]
Hi,

[firstDayOfWeek]="1" Works
firstDayOfWeek="1" Doesn't Work

Thanks

**Comment by dxbykov** [comment]
Hi,

If you don't use square brackets, Angular passes an html attribute value as a string. But, the dxScheduler component expects it to be a number.
