### ISSUE TITLE
Example request for DxScrollView, DxToolbar

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular2#35]
Learning Angular 2 from scratch, not sure how to get these to work.

Other components I can see in the examples.

**Comment by dxbykov** [comment]
Hi,

We need some more time to provide you with an example. Please bear with us.

**Comment by dxbykov** [comment]
After some research, it appears that DxScrollView doesn't transclude its content. I have created a corresponding issue #49. To create DxToolbar, you can use the code below:

in your host component TS code:
````js
import { Component } from '@angular/core';
import { DxToolbar } from 'devextreme-angular2';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [DxToolbar]
})
export class AppComponent {
  toolbarItems = [{
            location: 'before',
            widget: 'dxButton',
            options: {
                text: 'Press me',
                icon: 'refresh',
                onClick: function() {
                    alert("Hello world!");
                }
            }
        }
    ];
}
````
in your HTML template:
````html
<dx-toolbar [items]="toolbarItems"></dx-toolbar>
````

We believe this doesn't look natural for Angular 2. So I created one more issue on this regard #50.
