### ISSUE TITLE
DxForm binding broken

### ISSUE THREAD

**Issue by marcelgood** [DevExpress/devextreme-angular2#36]
The two-way DxForm binding doesn't seem to work at all. I've provided a repro sample at the following URL:

https://github.com/marcelgood/DxFormBindingIssue

See README.md for instructions on how to reproduce the issues.

**Comment by cohero** [comment]
I'm having this problem as well.

The two-way binding seems to be broken.  You can view a value in a bound dxForm with a control, but as soon as you attempt to edit value in the control, the data source is corrupted or deleted and a console error is thrown.

The sample above demonstrates it well.

**Comment by PiotrSliwinski** [comment]
Is there any progress with this?
I am having the same issue as described above.

**Comment by dxbykov** [comment]
We don't have any solutions or workarounds for the issue at the moment. We'll let you know once we have any.

**Comment by marcelgood** [comment]
Is there an update on this issue? When can we expect a build with a properly working DxForm etc.

**Comment by dxbykov** [comment]
We are working on this right now and will be able to give you an estimation soon.

**Comment by DokaRus** [comment]
Fixed in 1fcd4fc
