### ISSUE TITLE
Example PivotGrid ? 

### ISSUE THREAD

**Issue by ybarbaria** [DevExpress/devextreme-angular2#38]
Hello, 

Have you any example to use pivot grid with angular2 ?

Thx, 

YB

**Comment by dxbykov** [comment]
Hi,

We have an [example of using dxDataGrid](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html). dxPivotGrid doesn't have any specifics. You can use the **dx-pivot-grid** component with Angular 2 bindings.

**Comment by ybarbaria** [comment]
Sorry for the question shortly after I found solution by adaptive an example with jquery. 

Thx :)
