### ISSUE TITLE
DataGrid with angular2

### ISSUE THREAD

**Issue by 14Muhammad** [DevExpress/devextreme-angular2#39]
Hello,

Have you any example to use DataGrid with angular-2  while passing settings in json from component not directly in the view  ?

For example:
```
    <dx-data-grid [dataSource]="projects"
                  [allowColumnResizing]="true"
                  [hoverStateEnabled]="false"
                  [allowColumnReordering]="true"
                [searchPanel]="{visible: true}"
                  [paging]="{pageSize: 5}"
                 [pager]="{showInfo:true,showNavigationButtons:true,showPageSizeSelector:true}"
                  [rowAlternationEnabled]="true"
                  [selection]="{mode: 'none'}"
                  [editing]="{mode: 'form',allowUpdating: true,allowDeleting: true,allowAdding: true, texts:{addRow: 'Add a project'}}"
                  [export]="{enabled: true,fileName:'Projects',allowExportSelectedData: true}"
                  [groupPanel]="{visible: true}"
                  [filterRow]="{visible: true,applyFilter: 'auto'}"
                  [selection]="{mode: 'single'}">
    </dx-data-grid>
```

How we can pass json objects from component to view? while in above example json objects are directly mentioned in view.

Regards,
Ali

**Comment by dxbykov** [comment]
Hi,

You can find an example of complex property usage in our [sample app](https://github.com/DevExpress/devextreme-angular2/tree/master/examples/app). Please check how the chart's series property is bound in the [app.component.html](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html) file and declared in the [app.component.ts](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.ts) file.

**Comment by 14Muhammad** [comment]
Thanks for your prompt response.
Please let me know If I want to call some function from json object component. In your given example there are only binding for properties. What if I want to use some function e.g. onCellClick for dxDataGrid. 
How we can achieve this in Component of TypeScript?
Regards,
Ali

**Comment by dxbykov** [comment]
You can find an example in the [comment I've recently posted](https://github.com/DevExpress/devextreme-angular2/issues/42#issuecomment-232692909). Just replace the _onCellPrepared_ entry with the _onCellClick_ one.
