### ISSUE TITLE
DxDataGrid is too small in all browsers except for Google Chrome

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular2#45]
[Firefox](http://screencast.com/t/kPyxjoh0)
[Google Chrome](http://screencast.com/t/Jte9LK3E7K)

As a workaround, apply CSS like `style="height: 500px; width: 500px; display: block"` to your dx-data-grid element.

**Comment by GoshaFighten** [comment]
The same occurs with DxPivotGrid

**Comment by nightskylark** [comment]
The fix will be available in DevExtreme 16.2-alpha.1.
