### ISSUE TITLE
DxPopup example

### ISSUE THREAD

**Issue by Charlie2004** [DevExpress/devextreme-angular2#48]
HI,

Could you provide example how to use DxPopup. I was able to create empty Popup windows but was not able to populate it with any content inside it.
Many thanks.

**Comment by dxbykov** [comment]
Hi,

You can find it in [our example app](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.html).

You need to use a template for content as follows:

````html
    <dx-popup [showTitle]="true" title="Demo of dxPopup" [(visible)]="popupVisible">
        <div *dxTemplate="let t = data of 'contentTemplate'">
            <div>Hello from dxPopup</div>
        </div>
    </dx-popup>
````

Please, make sure you have imported the DxTemplate directive and added it to the host component directives list as [it is done in our sample](https://github.com/DevExpress/devextreme-angular2/blob/master/examples/app/app.component.ts).

**Comment by Charlie2004** [comment]
Great, Thank you for that. It worked.

**Comment by nhustak** [comment]
I had to change it to 'content' in the latest version of Angular to get it to work.  Found this by following the link provided by dxbykov.  Guessing it was changed and the code example was updated.
