### ISSUE TITLE
Can't set displayFormat for DxDateBox

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular2#51]
[Screen](http://screencast.com/t/k3gLIm4eu2cE)

[Project](https://github.com/GoshaFighten/DxDateBoxProject)

**Comment by GoshaFighten** [comment]
node_modules\devextreme-angular2\ui\date-box.js is missing the displayFormat option. Instead, it has the format and formatString options not declared in [http://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/Configuration/?version=16_1](http://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/Configuration/?version=16_1).

**Comment by StephanHartmann** [comment]
For me setting displayFormat is working.
Maybe you use wrong format strings?
Have you tried using "MMM" instead of "month"

as described  in the documentation link
==> https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx

**Comment by dxbykov** [comment]
@GoshaFighten We have a similar issue fixed #18. Please, make sure you are using the latest npm package.

**Comment by GoshaFighten** [comment]
@StephanHartmann , "month" is a correct format for Globalize which is used to format dates: [http://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/format/](http://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/format/)

@dxbykov , thank you. I used the official npm package.

`npm install devextreme-angular2@16.1.5-alpha --save`

This solves the issue.
