### ISSUE TITLE
DxMap click event - capture the location

### ISSUE THREAD

**Issue by swollaert** [DevExpress/devextreme-angular2#54]
I'm unable to find the solution to capture the click event on the dxMap component.
And being able to capture the location.

I thought it would be something like this.

```
<dx-map [(markers)]="markers" (click)="mapOnClick($e)"></dx-map>

  mapOnClick(e) {
    alert('mapOnClick location:' + e.location);
  }
```

But thats not working
Thanks in advance

**Comment by dxbykov** [comment]
Hi,

The 'click' event is a browser's DOM event, not a widget's one. You need to replace it with 'onClick'.

**Comment by swollaert** [comment]
I have tried this but its not working

`  
<dx-map (onClick)="mapOnClick()"></dx-map>

mapOnClick() {
    alert('onClick');
  }`

**Comment by dxbykov** [comment]
I have reproduced the issue on my side. It looks like a bug.

**Comment by anna-zhernovkova** [comment]
Hi!
 
I've researched the issue and have found that it is related to the incorrect dxMap behavior and is reproduced without Angular2 integration. I've created a bugreport in the DevExpress Support Center so you can track our progress with it [here](https://www.devexpress.com/Support/Center/Question/Details/T425488).
