### ISSUE TITLE
DxPopOver example

### ISSUE THREAD

**Issue by MichaelGaihede** [DevExpress/devextreme-angular2#55]
Could you please provide me with an example using the DxPopOver widget ?

Best regards and thanks

**Comment by dxbykov** [comment]
Hi,

The DxPopover widget usage is similar to the DxPopup one we have in our [examples](https://github.com/DevExpress/devextreme-angular2/tree/master/examples). It works on my side if specified as follows:

````html
    <dx-popover [(visible)]="popoverVisible" target="#myTarget">
        <div *dxTemplate="let t = data of 'contentTemplate'">
            <div>Hello from dxPopover</div>
        </div>
    </dx-popover>

    <dx-button id="myTarget" text="Show Popover" (onClick)="popoverVisible = !popoverVisible"></dx-button>
````

P.S. do not forget to import the DxPopover directive in your *.ts file.

**Comment by hmendezm** [comment]
Hi dxbykov,
How can I setup the Popover to remain open when hovering over it?

I am using mouseenter and mouseleave.

Best
hmendezm
