### ISSUE TITLE
Substituting a variable for an inline string in dx-list causes display to stop working

### ISSUE THREAD

**Issue by jtraband** [DevExpress/devextreme-angular2#59]
in the app.component.html if you replace this

````html
<dx-list [grouped]="true" style="height: 600px" [items]="[ { key: 'Notebook', items: [ 'Supernote JG867', 'Ultranote VP334', 'Meganote LS952' ] }, { key: 'Netbook', items: [ 'Supernet HY834', 'Ultranet KN354', 'Meganet ME830' ] } ]">
````
with 

````html
<dx-list [grouped]="true" style="height: 600px" [items]="listData">
````
where 

this.listData is defined in the app.component.ts using exactly the same javascript as above. The app no longer displays list data

**Comment by dxbykov** [comment]
Hi,

I didn't manage to reproduce the issue. It works correctly on my side. Please make sure that your TS code is recompiled after you have modified the code. If this doesn't help, would you show us the whole markup and TS code?

**Comment by jtraband** [comment]
My mistake - compile error - sorry. and thanks...
