### ISSUE TITLE
DxDataGrid Column Resizing

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#61]
Since 16.1.5 I can't resize columns. The cursor and the vertical line appears but i can't drag it.

**Comment by Angelminster** [comment]
My error.

**Comment by Angelminster** [comment]
Resizing works in firefox, not in chrome

**Comment by Aden-git** [comment]
Hello

The same issue was discussed in question #37. Add the following CSS style to solve it:
`dx-data-grid {
    display: block;
 }`
If it does not help, please let us know.

**Comment by dxbykov** [comment]
I think we should consider this as a bug. It should work without any workarounds. So, I'm reopening the issue.

**Comment by nightskylark** [comment]
The fix will be available in DevExtreme 16.2-alpha.1.
