### ISSUE TITLE
ReferenceError: DevExpress is not defined

### ISSUE THREAD

**Issue by Roman-Isachenko** [DevExpress/devextreme-angular2#62]
Hello. Can you help me with error:

> Exception: Call to Node module failed with error: ReferenceError: DevExpress is not defined

in

> node_modules\devextreme-angular2\core\dx.component.js:2:10

I add devextreme-angular2 to project with execute 

> npm i devextreme-angular2

In project i use webpack.

Thank you.

**Comment by davidalee** [comment]
Here's a similar issue that might help: https://github.com/DevExpress/devextreme-angular2/issues/12

**Comment by Aden-git** [comment]
Hello.

Note that devextreme-angular2 has dependence from [devextreme](https://www.npmjs.com/package/devextreme). Those scripts should be included to your project.

Take a look at the #12 and #47 threads for more details. Please let us know if that information does not help you.
