### ISSUE TITLE
DxChart zoomArgument(startValue, endValue) is missing

### ISSUE THREAD

**Issue by StephanHartmann** [DevExpress/devextreme-angular2#63]
Hi,

in your chart zooming sample of DevExtreme
[http://js.devexpress.com/Demos/WidgetsGallery/#demo/charts-advanced_features-zooming_and_scrolling
](url) there is a function
`zoomArgument(startValue, endValue)`
this seems not to be available via your Angular2 mappings

**Comment by Aden-git** [comment]
Hello,

You can get access to a DxChart instance by using the [ViewChild](https://angular.io/docs/ts/latest/api/core/index/ViewChild-var.html) decorator and the [AfterViewInit](https://angular.io/docs/ts/latest/api/core/index/AfterViewInit-class.html) lifecycle hook:

```typescript
import {
    ViewChild
} from '@angular/core';
```

```typescript
export class AppComponent implements AfterViewInit {
    @ViewChild(DxChart) DxChartComponent: DxChart;
    ngAfterViewInit(){
        this.DxChartComponent.instance.zoomArgument(800, 500);
    }    
    ......
}
```
