### ISSUE TITLE
DxMenu with adaptivityEnabled = true doesn't fire onItemClick event

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#64]
Hi,

It works in normal mode (adaptivityEnabled = false).

Regards

**Comment by Aden-git** [comment]
Hello,

I have reproduced this issue without the devextreme-angular 2 integration and created a [corresponding thread](https://www.devexpress.com/Support/Center/Question/Details/T412622) in our DevExpress Support Center. You can subscribe to updates in that thread to be notified of our progress with the issue.

This issue should be resolved as soon as the issue reported [here](https://www.devexpress.com/Support/Center/Question/Details/T412622) is addressed.

**Comment by Angelminster** [comment]
Closing: Not related to angular2 integration.

**Comment by Angelminster** [comment]
Works in 16.1.6
