### ISSUE TITLE
DxValidation on DxDateBox and DxNumberBox

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#65]
Hi,

ValidationMessage doesn't show in DxDateBox and DxNumberBox. 

The red exclamation doesn't show if isValid = false since the beginning. If is isValid = true and then false, it works.

Thank You

**Comment by dxvladislavvolkov** [comment]
We have reproduced this issue in dxNumberBox without the devextreme-angular 2 integration and created a [corresponding thread](https://www.devexpress.com/Support/Center/Question/Details/T415861) in our DevExpress Support Center. You can add that thread to favorites to be notified of our progress with the issue. 

As for the problem with dxDateBox, we could not reproduce it. Would you provide an example or a project where we it is reproduced so that we will research it on our side?

**Comment by Angelminster** [comment]
Hi,

With dxDateBox the problem is isValid = true, then false. Simple use case:
Is Valid = true, then false: shows the exclamation but doesn't show the message.

Another use case:
IsValid = false: shows the exclamation And the message.
IsValid = false, then true: it removes the exclamation: works.
IsValid = false,then true, then false: shows the exclamation but doesn't show the message.

Regards!

**Comment by dxvladislavvolkov** [comment]
Hello,
In the [example](http://plnkr.co/edit/c34vDGsu9o4snzoNFSiz?p=preview) these use cases do not work.
Can you provide additional information so that we can reproduce the problem?

**Comment by Angelminster** [comment]
Hi

Use this (change ¨ to `):

import {Component} from '@angular/core';
import {DxButton, DxDateBox, DxCheckBox} from 'devextreme-angular2';

@Component({
  selector: 'my-app',
  template:¨
    <div>
      <dx-date-box 
          [(value)]="date"
          [isValid] = "isValid()" 
          [validationError]="{message: 'Error'}"></dx-date-box>
    </div>
  ¨,
  directives:[
    DxButton,
    DxDateBox
  ]
})
export class App {
  date= null;
  constructor() {
  }
  
  private isValid()
  {
    return this.date != null;
  }
}

Step 1: Get a Value with DateBox
Step 2: Remove the Value (shows the exclamation but doesn't show the message.)

**Comment by Angelminster** [comment]
If a listen to isValid changes, dxDatebox set it to true when the date is in correct format. That could be the  problem. I want isValid = true when the date is in good shape AND myRules.

**Comment by Angelminster** [comment]
Maybe:
https://www.devexpress.com/Support/Center/Question/Details/T412868

**Comment by dxvladislavvolkov** [comment]
Hello

The validationError option is cleared when validation of dxDateBox is triggered. Our developers are searching for a way to fix this problem. You can add that [thread](https://www.devexpress.com/Support/Center/Question/Details/T418970) to favorites to be notified of our progress with the issue. 

In the meantime, you can use a workaround. Try to assign a value of validationError in the isValid function.

```html
<dx-date-box 
    [(value)] = "date"
    [isValid] = "isValid()"
    [validationError]="validationError">
</dx-date-box>
```

```javascript
private isValid() {
    this.validationError={message: "Error"};
    return this.date != null;
}
```

**Comment by Angelminster** [comment]
Thank You,
The WorkAround works :-)

**Comment by dxvladislavvolkov** [comment]
Hello @Angelminster 
Unfortunately, there is no way to fix this [issue](https://www.devexpress.com/Support/Center/Question/Details/T418970). You can use a workaround. 
Soon there will be available dxValidator where you can define your own validation rules and errors.

**Comment by Angelminster** [comment]
Then we should close this. We'll wait for validation rules to be implemented.

Thank You
