### ISSUE TITLE
DxChart OnHover Style

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#67]
Hi,

Devextreme-angular2 16.1.5. The stroke style when on hover in dxCharts does not work.

When I hover a bar or a part of the pie in a chart it adds  "fill="url(#DevExpress_121)" stroke="#5f8b95"" but it draws as transparent. 

In previous version worked as expected. 

Thank you

**Comment by Aden-git** [comment]
Hello
 
Could you please provide a code example to help us reproduce this behavior?

**Comment by Angelminster** [comment]
Hi,

The problem is the LocationStrategy of the Angular 2 Router. 

If you use **HashLocationStrategy** in bootstrap ( provide(LocationStrategy, { useClass: HashLocationStrategy }) ) it works. Inside your components you use "fill=url(#Devexpress_Number)" to get the pattern defined in the document.

If i use **PathLocationStrategry** the url(#Devexpress_Number) can't find the pattern and fill is transparent. 

Thank You,
Ángel

**Comment by dxvladislavvolkov** [comment]
Hello!
We have created [an example](http://plnkr.co/edit/N6irE0?p=preview).
Please clarify what steps we should perform to reproduce the error.

**Comment by Angelminster** [comment]
Hi,

In your example you have imported PathLocationStrategry instead of PathLocationStrategy (without the R)
In your config,js you have  '@angular/router': 'npm:@angular/router@2.0.0-rc.5/bundles/router.umd.js',
I think that package doesn't exist. Maybe it's "@angular/router": "3.0.0-rc.1". 

Try to inject this: constructor(private route: ActivatedRoute) {};

Thank You

**Comment by dxvladislavvolkov** [comment]
Hello,
We have reproduced this issue and created [a corresponding thread](https://www.devexpress.com/Support/Center/Question/Details/T429028) in our Support Center. You can add that thread to your favorites to be notified of our progress with the issue.

**Comment by Angelminster** [comment]
16.1.7 Solves it

**Comment by pavelgruba** [comment]
DevExtreme version 16.1.7 does not contain any changes that resolve this issue. Most likely, you checked this in the latest Chrome (54) where the URL resolve algorithm was changed. The problem is that the URL changes after the chart widget is created, so all links on resources appear to be broken (Chrome changed that in the latest version). At the moment, we cannot overcome the issue on our side.
