### ISSUE TITLE
DxChart Print/Export Menu

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#68]
Hi,

When the menu is hidden i can still click on the options. (print, export as pdf, gif, etc..)

When class="dx-export-menu-list" visibility="hidden" i can click the buttons.

In Firefox the background of the context menu is transparent until you hover all the buttons.

Thank You!

**Comment by Aden-git** [comment]
Hello,

I reproduced this issue in [Widgets Gallery](http://js.devexpress.com/Demos/WidgetsGallery/#demo/charts-data_binding-ajax_request) without a devextreme-angular2 project and created a [question](https://www.devexpress.com/Support/Center/Question/Details/T412904) in the DevExpress support center.
You can follow our progress [there](https://www.devexpress.com/Support/Center/Question/Details/T412904).

**Comment by Angelminster** [comment]
I close this then. Thank you.

**Comment by Angelminster** [comment]
Works in 16.1.6
