### ISSUE TITLE
DxDataGrid Max Columns Exceeded

### ISSUE THREAD

**Issue by Jlamb25** [DevExpress/devextreme-angular2#70]
I have a datagrid SIMILAR to the one outlined below. 

I get an error telling me that the max number of arguements for the $Promise has been exceeded. 
I have 52 columns to initialize, the exact same mark up for angular 1.x worked fine. 
Moving to angular 2, it does not seem to want to allow me to initalize the visibility of each column individually... 
If i take the column definitions out of the equation, then i see ALL columns which is something i obviously dont want to do. 

I think this may be a bug in the Angular 2 markup rendering. 
If it is just me being an idiot, then feel free to point out where im going wrong. 

<dx-data-grid
    (onInitialized) = "onInitialized($event)"
    [dataSource]='tradecosts'
    [paging]='{
        pageSize: 5
    }'
    [pager]= '{
        showPageSizeSelector: true,
        allowedPageSizes: [5, 10, 20],
        showInfo: true
    }'
    [showScrollbar]= 'always'
    [loadPanel]= "{
        height: 150,
        width: 400,
        text: 'Data is loading...'
        }"
    [columnChooser]= '{
                    enabled: true
                }'
    [headerFilter]= "{
                    visible: true
                }"
    [filterRow]= '{
                    visible: true,
                    applyFilter: "auto"
                }'
    [searchPanel]= '{
                    visible: true,
                    width: 240,
                    placeholder: "Search..."
                }'
    [columnAutoWidth]= 'true'
    [editing] ='{
                    mode: "batch",
                    allowUpdating: "true"
                }'
    [columns]= "[ { dataField: '1', visible: true },
                  { dataField: '2', visible: true },
                  { dataField: '3', visible: true },
                  { dataField: '4', visible: true },
                  { dataField: '5', visible: true },
                  { dataField: '6', visible: false},
                  { dataField: '7', visible: false },
                  { dataField: '8', visible: false },
                  { dataField: '9', visible: false },
                  { dataField: '10', visible: false },
                  { dataField: '11', visible: false },
....ANOTHER 40 columns

]"
    >
</dx-data-grid>

**Comment by Angelminster** [comment]
Hi,

See #22.

**Comment by Jlamb25** [comment]
Thanks Angel.
