### ISSUE TITLE
dxDataGrid instance not found. 

### ISSUE THREAD

**Issue by Jlamb25** [DevExpress/devextreme-angular2#73]
I have been fighting with an issue for a while now about how to call the refresh method from outside of the scope of where my dxDataGrid is rendered. 

To explain a little more: 

 @ViewChild(DxDataGrid) dataGrid:DxDataGrid
 refresh(){
       this.dataGrid.instance.refresh();
    }

I have a dxButton in my markup that calls this method without a problem. 

The problem occurs on updating the datagrid:
I have the grid in batch mode -> when i do an update, i make an ajax call to a web service. 
Within the Success function of my AJAX call i would like to refresh my data grid. 

as shown below:
 success: function (result) {
                            $.each(result, function (index, object) {
                                TRADECOSTS.push(object.Fields);
                            });
                            this.tradecosts = TRADECOSTS;
                            this.refresh()
                            console.log("Successfully refreshed datagrid source.");
                        },

The error message i get is: 
Object doesn't support property or method 'refresh'

////////////////////////////////////////////////////////////////////

If i were to hazard a guess, i would say that the problem is occuring because the dxdatagrid lies out of the scope when called from the AJAX success function. 
What i cannot figure out, is how to make this dxDataGrid available within the scope of my AJAX function.

If anyone has any ideas, I would very much appreciate it

**Comment by Aden-git** [comment]
Hello,
 
It looks like the issue appears due to the `this.refresh()` function in the "success" handler, not `this.dataGrid.instance.refresh();`, because the "this" variable has a wrong context. Please check this. If this doesn't help, provide us with a simple working code sample for additional research.

**Comment by Jlamb25** [comment]
Hi Aden, 
I get the same error "Unable to get property 'instance' of undefined or null reference."
My Ajax call is within the OnRowUpdating function of the dxDataGrid.

The Below class is a stripped down "bare bones" replication of the issue. 


In my App.Component.ts

export class AppComponent implements OnInit{

@ViewChild(DxDataGrid) dataGrid:DxDataGrid

onRowUpdating(row){

var refreshedTradeCosts = [];
                    $.ajax({
                        type: 'GET',
                        url: "myURL",
                        contentType: "application/json",
                        dataType: "json",
                        async: false,
                        success: function (result) {
                            $.each(result, function (index, object) {
                                TRADECOSTS.push(object.Fields);
                            });

                           //This line is where my code fails. 
                            this.dataGrid.instance.refresh();

                            },
                        error: function (result) {
                                                 }
                    });
}
}





Below this is the Markup for my dataGrid. In my App.Component.HTML:

<dx-data-grid
    (onInitialized) = "onInitialized($event)"
    [dataSource]='tradecosts'
    [paging]='{
        pageSize: 5
    }'
    [pager]= '{
        showPageSizeSelector: true,
        allowedPageSizes: [5, 10, 20],
        showInfo: true
    }'
    [showScrollbar]= 'always'
    [loadPanel]= "{
        height: 150,
        width: 400,
        text: 'Data is loading...'
        }"
    [columnChooser]= '{
                    enabled: true
                }'
    [headerFilter]= "{
                    visible: true
                }"
    [filterRow]= '{
                    visible: true,
                    applyFilter: "auto"
                }'
    [searchPanel]= '{
                    visible: true,
                    width: 240,
                    placeholder: "Search..."
                }'
    [columnAutoWidth]= 'true'
    [editing] ='{
                    mode: "batch",
                    allowUpdating: "true"
                }'
    [columns]= "dataGridColumns"
    (onRowUpdating)="onRowUpdating($event)"
    >
</dx-data-grid>

**Comment by Aden-git** [comment]
Hello,

Please try to implement the following code:

```typescript
export class AppComponent implements OnInit{

    @ViewChild(DxDataGrid) dataGrid:DxDataGrid;

    onRowUpdating(row){
        let that = this, // Cache "this" 
            refreshedTradeCosts = [];
        $.ajax({
            type: 'GET',
            url: "myURL",
            contentType: "application/json",
            dataType: "json",
            async: false,
            success: function (result) {
                $.each(result, function (index, object) {
                    TRADECOSTS.push(object.Fields);
                });
                // Get access to dataGrid instance from cached variable
                that.dataGrid.instance.refresh();
            },
            error: function (result) {
            }
        });
    }
}
```

**Comment by Jlamb25** [comment]
Worked like a charm. 

Thanks again Aden.
