### ISSUE TITLE
DxDataGrid CellTemplate Not Working Properly

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#74]
Hi,

When a dxTemplate is defined inside a dxDataGrid and the datasource is not ready before first load it fails drawing the grid. I hope that you can reproduce the issue introducing the dxDataGrid dataSource from a service or setting it inside ngAfterViewInit(). 

The error: **n.owner is not a function at DxTemplate.<anonymous> (dx.all.js:10) from _cleanPreviousContent -> o.cleanData -> _cleanTemplates**

It seems that you are cleaning content of nothing.

If the dataSource is ready then it works as expected. If you have a dataSource before first load and then you change it, it works too.

Thank You

**Comment by Angelminster** [comment]
¿#85?

**Comment by Aden-git** [comment]
Hello,

Yes, looks like #85 should fix it. We will research it as soon as possible.

**Comment by Angelminster** [comment]
It seems that #85 Fixed this.
