### ISSUE TITLE
Using templates causes exceptions in certain cases

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular2#75]
[https://github.com/GoshaFighten/Bug/tree/master/Angular2TemplateIssue](https://github.com/GoshaFighten/Bug/tree/master/Angular2TemplateIssue)
This project raises the `Expression has changed after it was checked` exception. To avoid it, uncomment the `enableProdMode();` code in the `main.ts` file.

**Comment by dxbykov** [comment]
Hi,

Thank you for pointing this out. We are already aware of this issue and have a corresponding bug reported #4
