### ISSUE TITLE
Despite #17 fix, named templates seems to be still broken

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular2#79]
On the positive side, I am making great progress rewriting a jquery ui/jquery mobile knockout app into a dev express angular 2 app.

I have tried using a named template in dx-tab-panel and dx-context-menu and both of them error with the same message "itemElement.empty is not a function".

I also tried to replicate the custom template for dx-select-box (the one with the tv panels). I can't seem to get syntax right with the requirement for there to be a textbox in the template.

http://js.devexpress.com/Demos/WidgetsGallery/#demo/editors-select_box-overview

**Comment by Angelminster** [comment]
Solved? #85. #98

**Comment by dxvladislavvolkov** [comment]
Hello!
Yes, we fixed the issue with named templates, but the issue with the fieldTemplate is not related to the problem discussed here. 
We will research it in another thread #106
