### ISSUE TITLE
dxLookup columns title

### ISSUE THREAD

**Issue by Massaru** [DevExpress/devextreme-angular2#82]
Hi team!

How do I show them?

best regards!

**Comment by dxvladislavvolkov** [comment]
Hello!
What do you mean by the columns in the dxLookup?

**Comment by Massaru** [comment]
Hi,

the code:

`<dx-lookup [dataSource]="heroes" [formControl]="hero" [(value)]="selectedHero" [searchExpr]="['name', 'power', 'id']" displayExpr="name" displayValue="id">
        <div *dxTemplate="let item = data of 'itemTemplate'">
            {{item.id}} - {{item.name}} - {{item.power}}
        </div>
    </dx-lookup>`

In searchExpr I set up three columns to search for references, and put in dxTemplate write these 3 columns, I would like to see the titles of the columns that are in dxTemplate.


This is somehow possible?


best regards!

**Comment by Massaru** [comment]
I found some examples in AngularJS 1.x but could not write in Angular 2.

**Comment by dxvladislavvolkov** [comment]
Hello!

You need additional customization to add a title to dxTemplate. 
For example:

`<dx-lookup [dataSource]="heroes" (onContentReady)="ready()" [formControl]="hero"  [(value)]="selectedHero" [searchExpr]="['name', 'power', 'id']" displayExpr="name" displayValue="id"> <div *dxTemplate="let item = data of 'itemTemplate'"> {{item.id}} - {{item.name}} - {{item.power}} </div> </dx-lookup>`

`ready() {
     $('.dx-scrollable').prepend('<div>Id - name - power</div>');
 }`

**Comment by Massaru** [comment]
Worked like a charm!

thank you dxvladislavvolkov!
