### ISSUE TITLE
dxDataGrid with webapi

### ISSUE THREAD

**Issue by Massaru** [DevExpress/devextreme-angular2#84]
Hi team,

This [project](https://github.com/Massaru/dxDataGridPromiseData) simulates a webapi service returning a data promise.

Why dxDataGrid does not show the data the first time?

I need to click the refresh button to display the data, but with it he repeated the trip in "simulated webapi".

How to work?

Best regards!

**Comment by dxvladislavvolkov** [comment]
Hello,

The Load method should return promis. 
In your example, the method returns "undifined" until data is loaded

For example: 
```load: (loadOptions: any) => {
    return this.heroService.getHeroes()
},```

```getHeroes() {
    return new Promise<Hero[]>(resolve => resolve(HEROES));
  }```

**Comment by Massaru** [comment]
Hi,

thank you dxvladislavvolkov!
