### ISSUE TITLE
Formatting and localize dx-date-box

### ISSUE THREAD

**Issue by LoganFitz** [DevExpress/devextreme-angular2#86]
Hi,
I try to find out how to set the dx-date-box to a display format like "dd-MM-YYYY" and switch to locale de.
Some settings are working:
`<dx-date-box [pickerType]="native" [value]="currentDate" [showClearButton]="true" [displayFormat]='{type: "longDate"}'></dx-date-box>`

but if I use for instance  `[displayFormat]='{skeleton: "dd-MM-YYYY"}'` only a text box without anything appears.
Where can I find the new rules to customize the widgets?
Please give me an excample how to switch the locale to "de-DE" and set the behavior of the dx-date-box.
Thanks, Michael

**Comment by dxvladislavvolkov** [comment]
Hello,
You need to use the globalize library. 
Read [here](https://www.devexpress.com/Support/Center/Example/Details/T410725) for details on how to localize DevExtreme widgets.

This example illustrates how to assign a format value to the displayFormat option:
`<dx-date-box displayFormat="dd-MM-YYYY"></dx-date-box>`

**Comment by LoganFitz** [comment]
Hi,
implementing all of globalization in the proper order, localization works and also displayFormat="dd-MM-YYYY".
Thanks a lot, Michael

**Comment by Laoujin** [comment]
@LoganFitz : Could you provide an example what you did exactly to make this work?

The link provided by dxvladislavvolkov is for Knockout which Angular obviously isn't...
