### ISSUE TITLE
Using dx-validator for validation as in angularjs.

### ISSUE THREAD

**Issue by sreejithsdev** [DevExpress/devextreme-angular2#87]
I am using devextreme-angular2 .In my textbox control i need to apply 'required' validations
<dx-text-box id="divjobName" class="col-sm-7" [(value)]="job.jobName" ></dx-text-box>

on submit the function is as follows

onSubmit(event) {
   var result= event.validationGroup.validate();
} 

But how can i validate it through dx-validator
<dx-validator name='Job Name'    validationRules="[{ type: 'required', message: 'Specify your email or phone number!' }]" ></dx-validator>

**Comment by dxvladislavvolkov** [comment]
Hello, 
It looks like this issue is a duplicate of [#30](https://github.com/DevExpress/devextreme-angular2/issues/30)
