### ISSUE TITLE
DxDataGrid onCellClick

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular2#89]
Hi,

This **important** event is not raised. 

(onRowClick)='onRowClick($event)' -> OK
(onCellClick)='onCellClick($event)' -> FAIL
(onSelectionChanged)='onSelectionChange($event)' -> OK
(onContextMenuPreparing)='onContextMenuPreparing($event)' -> OK
(onInitialized)='onInitializedDataGrid($event)' -> FAIL (in #14)
(onRowPrepared)='onRowPrepared($event)' -> OK
(onCellPrepared)='onCellPrepared($event)' -> OK

Thank you

**Comment by DokaRus** [comment]
Hi!
 
I've researched the issue and have found that it is related to the incorrect dxDataGrid behavior and is reproduced without Angular2 integration. I've created a bugreport in the DevExpress Support Center so you can track our progress with it [here](https://www.devexpress.com/Support/Center/Question/Details/T425421).

**Comment by Angelminster** [comment]
Hi,

The hotFix doesn't seem to fix the event inside the integration.

Regards

**Comment by DokaRus** [comment]
Hi,
I apologize for any inconvenience this issue might have caused you. 
It appears that we've published a wrong hotfix for this issue. We've re-uploaded the correct hotfix. Please download it, upgrade your app, and check if it solves the issue.
I've attached a simple example that demonstrates that the "onCellClick" dxDataGrid event works well now.
[issue089.zip](https://github.com/DevExpress/devextreme-angular2/files/476578/issue089.zip)

**Comment by Angelminster** [comment]
With this new hotfix works :-)!

Thanks!

**Comment by DokaRus** [comment]
You're always welcome!
