### ISSUE TITLE
Dx TabPanel- dxtemplate

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular2#98]
<dx-tab-panel [dataSource]="Model.SutGridDataSource" [height]="200" [width]="100">

            <div *dxTemplate="let t = data of 'customtemp'">
                <p>Tab panel</p>
                <p>Açıklamalar...........</p>
            </div>

        </dx-tab-panel>

This codde is not work?

**Comment by dxvladislavvolkov** [comment]
Hello!
Use "itemTemplate" and "itemTitleTemplate" for templates names.
Soon, it will be possible to use named templates.

**Comment by Angelminster** [comment]
Same as #85?

**Comment by dxvladislavvolkov** [comment]
Yes, you are right. This issue should be fixed in #85

**Comment by dxvladislavvolkov** [comment]
Hello!
We fixed the issue with named templates. 
[Here](http://plnkr.co/edit/Iupo4X?p=preview) you can see the example of using them.

**Comment by Angelminster** [comment]
Hello,

That's Great. Is this inside the 16.1.6 released 5 days ago?

**Comment by dxvladislavvolkov** [comment]
Yes, you need to update your version of the scripts.

**Comment by sanket360** [comment]
@dxvladislavvolkov plunker example provided above is not working. can you please check again?

**Comment by dxvladislavvolkov** [comment]
Hello!
I've updated the example. You can see it [here](http://plnkr.co/edit/4kKPxI?p=preview)

**Comment by sanket360** [comment]
Thanks @dxvladislavvolkov :+1:
